export 'custom_snackbar.dart' show customSnackbar;
export 'download_notification.dart' show downloadNotification;
export 'download_qr_in_i_o_s.dart' show downloadQrInIOS;
export 'download_qrcode.dart' show downloadQrcode;
export 'email_validation.dart' show emailValidation;
export 'open_settings.dart' show openSettings;
export 'phone_validation.dart' show vietnamPhoneValidation;
export 'save_contact.dart' show saveContact;
export 'write_n_f_c_action.dart' show writeNFCAction;
