// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLl-Fmb3RIQz74YkQTLtp9L9vp2mXmK0',
    appId: '1:1000186163055:web:9bcb897a7d4795fb7a429a',
    messagingSenderId: '1000186163055',
    projectId: 'me-and-you-1228b',
    authDomain: 'me-and-you-1228b.firebaseapp.com',
    storageBucket: 'me-and-you-1228b.appspot.com',
    measurementId: 'G-JGXXJYZ7LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBop423WMseywU35lPhdftnMvYeXedMJ7s',
    appId: '1:1000186163055:android:e4f8114023cd36747a429a',
    messagingSenderId: '1000186163055',
    projectId: 'me-and-you-1228b',
    storageBucket: 'me-and-you-1228b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjM3p5dhQS9ssUvzabMpwjDNj4cdva2X0',
    appId: '1:1000186163055:ios:d2c02248b72982e27a429a',
    messagingSenderId: '1000186163055',
    projectId: 'me-and-you-1228b',
    storageBucket: 'me-and-you-1228b.appspot.com',
    androidClientId: '1000186163055-ap2mmoodv9g06qo3fk11boc3d290d4vj.apps.googleusercontent.com',
    iosClientId: '1000186163055-o253qn5ehbunsdjgrtt0f78cpnpkanca.apps.googleusercontent.com',
    iosBundleId: 'vn.ntiot.meandyou',
  );
}
